### PR TITLE
Added Bottom navigation bar

### PR DESCRIPTION
**Pull request by BRO3886**
Solves #2 

* Added bottom nav bar
* defined project structure

- [x]  I have read the Code Of Conduct.

- [x]  I have followed all the steps of submission properly.

### CODE REVIEW

**Comment by jayskhatri** [comment]
Hey @BRO3886 

Thanks for sending PR

One of our maintainers will review it soon! But before that can you please go through the [guidelines](https://github.com/clubgamma/Spotify-UI-Clone-Flutter/blob/master/CONTRIBUTING.md) and change accordingly with the checkbox in your PR message :)

**Comment by BRO3886** [comment]
updated the comment ✔️

**Comment by BRO3886** [comment]
https://hacktoberfest.digitalocean.com/hacktoberfest-update?updated

Please update according to the required guidelines

**Review by harshptl14 — APPROVED** [review]
Thanks,@BRO3886, for opening the pull request! 👏

I have reviewed your pull request thoroughly, and it's perfect!🚀

Sorry for the delay in reviewing😶

Star ⭐ this project would be great! You can also [tweet](https://twitter.com/share?text=Contributed+to+awesome+projects+at+@club_gamma&url=https://clubgamma.github.io/hacktoberfest) about your contributions🤟
Join the [discord channel of club gamma🙌](https://discord.gg/kjnp6wU)

**Pull request merged**
