### PR TITLE
Added splash screen

### PR DESCRIPTION
**Pull request by BRO3886**
* Added a native splashscreen which shows the spotify logo before flutter view gets rendered

Solves #1 

- [x]  I have read the Code Of Conduct.

- [x]  I have followed all the steps of submission properly.

### CODE REVIEW

**Comment by jayskhatri** [comment]
Hey @BRO3886 
Thanks for sending PR
Please go through this https://github.com/clubgamma/Spotify-UI-Clone-Flutter/pull/13#issuecomment-702002448

happy hacking :)

**Comment by BRO3886** [comment]
Updated the comment

**Comment by BRO3886** [comment]
* This is a native splash screen

**Comment by BRO3886** [comment]
https://hacktoberfest.digitalocean.com/hacktoberfest-update?updated

Can you add the required tags to qualify as per the new guidelines?

**Review by harshptl14 — APPROVED** [review]
Thanks,@BRO3886, for opening the pull request! 👏

I have reviewed your pull request thoroughly, and it's perfect!🚀

**Pull request merged**
